input <- read.table("C:\\stat_learning\\household_power_consumption.txt",header=T,comment.char = "",sep=";",na.string="?",nrow=5)
classes <- sapply(input,class)
input <- read.table("C:\\stat_learning\\household_power_consumption.txt",header=T,comment.char = "",sep=";",na.string="?",colClasses=classes)
attach(input)
names(input)
dim(input)
x <- paste(Date, Time)
input$DateTime <- strptime(x,"%d/%m/%Y	%T")
data_feb <- subset(input,Date == "1/2/2007" | Date == "2/2/2007")

png(filename = "plot4.png",
    width = 480, height = 480)

attach(data_feb)
par(mfrow=c(2,2))
with(data_feb,plot(DateTime,Global_active_power,type="l",ylab= "Global Active Power",xlab=""))
with(data_feb,plot(DateTime,Voltage,type="l",ylab="Voltage",xlab="datetime"))
with(data_feb,plot(DateTime,Sub_metering_1,type="l",ylab=" Energy sub metering",xlab="",mar=c(4,2,1,1)))
lines(DateTime,Sub_metering_2,col="red",type="l")
lines(DateTime,Sub_metering_3,col="blue",type="l")
legend("topright",lwd=1,bty="n",col=c("black","red","blue"),legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),cex=0.7)
with(data_feb,plot(DateTime,Global_reactive_power,type="l",ylab="Global_reactive_power",xlab="datetime"))
dev.off()
